services:
  db:
    image: postgres:15-alpine
    container_name: ae_postgres_db
    restart: always
    
    ports:
      - "5434:5432"
      
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      
    # Use the .env file to pass the values into the service
    env_file:
      - ./.env
      
    # Persist the data on your local machine to prevent data loss on container restart
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
